### ISSUE TITLE
Create-Trip 

### ISSUE THREAD

**Issue by Manishvishe** [Manishvishe/Travelsphere-AI-Trip-Planner#1]
Feature Request: Create Trip Page for Users

I need to add a "Create Trip" page to the AI Trip Planner. This page should allow users to:
 -Add preferred destinations.
 -Choose Budget.
 -Select No. of Days
 -Customize their trips with an easy-to-use interface.

**Comment by adeshshelar** [comment]
Hi, I’ll be working on this feature to implement the "Create Trip" page.
