### ISSUE TITLE
View-Trip

### ISSUE THREAD

**Issue by Manishvishe** [Manishvishe/Travelsphere-AI-Trip-Planner#5]
- The View Trip section needs improvement to display trip details clearly.
- Users should view information like destinations, dates, costs, and activities.
- The current layout is not user-friendly, causing confusion when viewing trips.
- Enhance the UI/UX for a more intuitive user experience.

**Comment by KunalGaikwad1** [comment]
Hi!, I am going to work on this feature I 'll redesign the View Trip section with a more structured layout, clearly displaying destinations, dates, costs, and activities. My focus will be on improving usability and clarity to ensure a seamless user experience.

**Comment by KunalGaikwad1** [comment]
Added new View-trip Feature #6 
![Screenshot 2024-10-23 182900](https://github.com/user-attachments/assets/6a984452-537c-4b04-9ef6-27df878dc413)
